name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment: 
      name: production
      url: ${{ secrets.PRODUCTION_URL }}

    steps:
    - name: Store SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRODUCTION_SSH }}

    - name: Add Known Host
      run: |
        ssh-keyscan -H ${{ secrets.PRODUCTION_IP }} >> ~/.ssh/known_hosts

    - name: Update Code
      run: |
        ssh ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_IP }} "cd ${{ secrets.PRODUCTION_DIR }} && git pull"

    - name: Update Composer Packages
      run: |
        ssh ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_IP }} "cd ${{ secrets.PRODUCTION_DIR }} && php83 /usr/local/bin/composer install --no-interaction"

    - name: Run Migrations
      run: |
        ssh ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_IP }} "cd ${{ secrets.PRODUCTION_DIR }} && php83 artisan migrate --force"

    - name: Build CSS and JS
      run: |
        ssh ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_IP }} "cd ${{ secrets.PRODUCTION_DIR }} && npm run build"
