name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, Production]
    
    environment: 
      name: production
      url: "${{ secrets.PRODUCTION_URL }}"

    defaults:
      run:
        working-directory: "${{ secrets.PRODUCTION_DIR }}"

    steps:
    - name: Update Code
      run: git pull

    - name: Update Composer Packages
      run: php83 /usr/local/bin/composer install --no-interaction

    - name: Run Migrations
      run: php83 artisan migrate --force

    - name: Build CSS and JS
      run: npm run build
