name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, Production]
    
    environment: 
      name: Production
      url: https://to.jidb.net

    steps:      
    - name: Update Code
      run: "cd ${{ secrets.PRODUCTION_DIR }} && sudo -u ${{ secrets.PRODUCTION_USER }} git pull"

    - name: Update Composer Packages
      run: "cd ${{ secrets.PRODUCTION_DIR }} && sudo -u ${{ secrets.PRODUCTION_USER }} php83 /usr/local/bin/composer install --no-interaction"

    - name: Run Migrations
      run: "cd ${{ secrets.PRODUCTION_DIR }} && sudo -u ${{ secrets.PRODUCTION_USER }} php83 artisan migrate --force"

    - name: Update NPM Packages
      run: "cd ${{ secrets.PRODUCTION_DIR }} && sudo -u ${{ secrets.PRODUCTION_USER }} npm install"
      
    - name: Build CSS and JS
      run: "cd ${{ secrets.PRODUCTION_DIR }} && sudo -u ${{ secrets.PRODUCTION_USER }} npm run build"
